### ISSUE TITLE
About the paper experiment result.

### ISSUE THREAD

**Issue by jifeng35** [zamling/PSALM#21]
It's a really nice work.But after reading your thesis, I am wondering why the results of experiment are different in two tabel.(RefCOCO PSALM, in the first table, the cIoU is 76.1, but in the second one the cIoU is 83.6,84.7,81.6)
Looking forward to your earliest reply.
![Screenshot 2024-10-18 at 09 19 15](https://github.com/user-attachments/assets/1873af35-e16a-4eb6-b968-86937ccfcc65)
![Screenshot 2024-10-18 at 09 22 54](https://github.com/user-attachments/assets/8a0ca0fb-3468-483f-90da-bef62568d3ff)

**Comment by zamling** [comment]
Hi @jifeng35 
We do all ablation experiments in a shorter training iteration, as shown in following table (Tab. 16 in appendix).
![image](https://github.com/user-attachments/assets/605d7c5d-4a19-454e-aef1-c19ae1dd23bf)

**Comment by jifeng35** [comment]
Got it! Thank you very much!
Then you can close the issue🫡
