### ISSUE TITLE
How to fine-tune on my own dataset

### ISSUE THREAD

**Issue by YYGe01** [zamling/PSALM#7]
Hello,
     I would like to add some of my own datasets to fine-tune based on PSALM.
Is it better to fine-tune all parameters or fine-tune some parameters? What can be done specifically? 
Thank you.

**Comment by zamling** [comment]
Hi @YYGe01 
PSALM training strategy is only freezing vision tower (swin base) and training other paramethers. So may be you can follow this
:)

**Comment by YYGe01** [comment]
> Hi  你好@YYGe01 PSALM training strategy is only freezing vision tower (swin base) and training other paramethers. So may be you can follow thisPSALM训练策略只是冻结视野塔（swin基地）并训练其他参数。所以也许你可以遵循这个 :)

thanks,
my dataset is very small, with possibly only a few hundred samples, and it is an uncommon dataset. Therefore, would it be better to fine-tune directly on Psalm? Moreover, since GPU resources are limited, I’m thinking if it’s possible to use techniques like LoRa for fine-tuning.

**Comment by zamling** [comment]
I have not tried to train PSALM in a single GPU.
May be LoRA is a potential solution
