### ISSUE TITLE
Visualization scripts for evaluation

### ISSUE THREAD

**Issue by YunzeMan** [zamling/PSALM#9]
Thanks a lot for your great work! I am able to evaluation the model using the provided scripts.

However, I'm wondering what is the correct way to visualize the model inference results. For instance, for refCOCO dataset, is there a way to visualize the output segmentation masks? (To create demonstration figures like your Figure 1 in the paper.)

**Comment by zamling** [comment]
Hi @YunzeMan 
There are lots of ways to visualize results. For example
1. you can directly add mask onto the original image
```
pred_mask = pred_masks[[idx_], :][0].astype(np.bool_)
save_img = copy.deepcopy(img)
save_img[pred_mask] = (
        img * 0.5
        + pred_mask[:, :, None].astype(np.uint8) * np.array([0, 0, 255]) * 0.5
)[pred_mask]
save_img = cv2.cvtColor(save_img, cv2.COLOR_RGB2BGR)
cv2.imwrite(f'./example.jpg', save_img)
```

2. Using detectron2 Visualizer, please check more details in detectron2 official documents
```
from detectron2.utils.visualizer import Visualizer
```
